#!/usr/bin/env bash
# Sets up 404 error page

# Update and install nginx
sudo apt-get update -y
sudo apt-get install -y nginx

# Allow Nginx HTTP traffic through the firewall
sudo ufw allow 'Nginx HTTP'

# Create custom 404 page content
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# Nginx configuration to handle 404 errors
config="server {
        listen 80 default_server;
        listen [::]:80 default_server;
        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;
        error_page 404 /404.html;
        server_name _;

        location / {
                try_files \$uri \$uri/ =404;
        }

        location /redirect_me {
                return 301 https://github.com/VeronicahWanjuu;
        }
}"

# Set up the default webpage and the configuration file for Nginx
echo "Holberton School" | sudo tee /var/www/html/index.html
echo "$config" | sudo tee /etc/nginx/sites-available/default

# Restart Nginx to apply changes
sudo service nginx restart

